name: shopping_app
description: Brand Shopping Application - Premium E-commerce Experience
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  badges: ^3.1.2
  pinput: ^5.0.0
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Functional Programming
  fpdart: ^1.1.0
  
  # Routing
  go_router: ^14.6.2
  
  # Network
  dio: ^5.7.0
  connectivity_plus: ^6.1.0
  
  # Local Storage
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  
  # Authentication
  google_sign_in: ^6.2.2
  
  # Push Notifications
  onesignal_flutter: ^5.2.7
  
  # Utils
  intl: ^0.20.1
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  share_plus: ^10.1.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  
  # Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.5.0
  
  # Animations
  flutter_animate: ^4.5.0
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
